name: Pull Request Verification

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]

jobs:
  biome:
    if: github.event.pull_request.draft == false
    name: Biome
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          fetch-depth: 0
          clean: false
      - run: nix run .#nix-develop .#workflow
      - run: biome check --reporter=github .

  knip:
    if: github.event.pull_request.draft == false
    name: Knip
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          fetch-depth: 0
          clean: false
      - run: nix run .#nix-develop .#workflow
      - run: ./node_modules/.bin/knip

  typescript:
    if: github.event.pull_request.draft == false
    name: TypeScript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          fetch-depth: 0
          clean: false
      - run: nix run .#nix-develop .#workflow
      - run: ./node_modules/.bin/tsc --build
